In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('tmdb_5000_movies.csv')

In [3]:
df.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
df.groupby('original_language')

In [7]:
df.groupby('original_language').mean()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
original_language,,,,,,,
af,3.000000e+06,868.000000,2.504169,9.879971e+06,94.000000,6.900000,94.000000
ar,0.000000e+00,83505.000000,4.723389,0.000000e+00,92.000000,7.300000,53.500000
cn,1.072641e+07,109470.500000,10.631343,3.374016e+07,104.750000,6.500000,220.916667
cs,0.000000e+00,185196.000000,1.286848,0.000000e+00,104.500000,5.650000,12.000000
da,9.742857e+06,33440.714286,17.663925,2.989889e+07,121.428571,7.128571,450.428571
de,8.616354e+06,63369.518519,10.151382,1.396191e+07,107.777778,6.325926,242.444444
el,0.000000e+00,38810.000000,28.858238,1.101970e+05,94.000000,6.900000,332.000000
en,3.039436e+07,55788.758047,22.177435,8.647885e+07,106.471581,6.065683,719.023751
es,5.847683e+06,73720.937500,13.330804,1.865218e+07,109.093750,6.659375,301.875000
fa,2.450000e+05,38974.000000,5.664415,2.250000e+05,102.250000,7.375000,155.250000
fr,8.480997e+06,62312.171429,10.299542,1.246151e+07,105.114286,6.430000,228.828571
he,6.666667e+05,16428.333333,5.364953,3.708616e+06,108.000000,7.400000,112.666667
hi,1.715789e+06,86905.526316,2.994144,7.447231e+06,138.631579,6.010526,44.000000
hu,0.000000e+00,41508.000000,1.906807,0.000000e+00,140.000000,6.500000,28.000000
id,1.050000e+06,109003.500000,24.586253,2.274881e+06,108.000000,7.400000,632.500000
is,1.000000e+01,217708.000000,1.617943,1.100000e+01,85.000000,6.900000,26.000000
it,2.967859e+06,64481.857143,17.818268,3.029494e+06,114.461538,7.028571,403.928571
ja,1.429361e+07,53894.250000,25.663788,6.602892e+07,122.500000,7.050000,715.750000
ko,1.429091e+07,82569.545455,19.488720,2.535645e+07,123.727273,6.672727,588.818182
ky,0.000000e+00,295914.000000,0.077873,0.000000e+00,135.000000,0.000000,0.000000
nb,3.500000e+06,46146.000000,12.982319,4.159678e+06,103.000000,6.700000,583.000000
nl,7.375000e+06,12169.500000,4.768978,6.680779e+06,118.250000,7.175000,92.750000
no,8.000000e+05,14451.000000,11.205726,1.984662e+06,91.000000,6.100000,311.000000
pl,2.159280e+06,209274.000000,13.265432,1.070000e+07,80.000000,7.100000,260.000000
ps,4.600000e+04,14757.000000,1.447734,0.000000e+00,83.000000,6.300000,32.000000
pt,1.133333e+06,136400.444444,11.309857,4.026498e+06,109.888889,6.388889,321.444444
ro,4.262550e+05,173237.500000,4.798877,5.928915e+05,108.500000,3.650000,78.000000
ru,1.397273e+07,105219.000000,7.567724,9.510074e+06,116.727273,6.354545,95.181818
sl,0.000000e+00,385636.000000,0.061248,0.000000e+00,83.000000,6.000000,1.000000
sv,5.000000e+06,13241.200000,7.347336,0.000000e+00,119.000000,7.060000,87.000000
ta,0.000000e+00,270824.500000,0.368283,0.000000e+00,162.500000,5.850000,4.000000
te,4.000000e+07,256040.000000,16.254032,1.000000e+08,159.000000,7.500000,135.000000
th,4.833333e+06,17554.666667,7.230292,1.203408e+07,130.333333,5.966667,108.333333
tr,1.000000e+07,11818.000000,1.465762,0.000000e+00,122.000000,4.300000,7.000000
vi,1.300000e+06,25784.000000,0.072066,6.390000e+05,135.000000,5.000000,1.000000
xx,1.200000e+07,62204.000000,6.537986,5.526056e+07,100.000000,7.100000,109.000000
zh,2.202560e+07,107819.222222,8.996167,4.173498e+07,116.074074,6.300000,146.592593

In [8]:
df.groupby('original_language').mean().loc['ja']

budget          1.429361e+07
id              5.389425e+04
popularity      2.566379e+01
revenue         6.602892e+07
runtime         1.225000e+02
vote_average    7.050000e+00
vote_count      7.157500e+02
Name: ja, dtype: float64

In [9]:
df[df['original_language']== 'ja' ]

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
97,15000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",NaN,315011,"[{""id"": 1299, ""name"": ""monster""}, {""id"": 7671,...",ja,シン・ゴジラ,From the mind behind Evangelion comes a hit la...,9.476999,"[{""name"": ""Cine Bazar"", ""id"": 5896}, {""name"": ...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2016-07-29,77000000,120.0,"[{""iso_639_1"": ""it"", ""name"": ""Italiano""}, {""is...",Released,A god incarnate. A city doomed.,Shin Godzilla,6.5,143
1471,41677699,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",NaN,12429,"[{""id"": 456, ""name"": ""mother""}, {""id"": 1357, ""...",ja,崖の上のポニョ,"The son of a sailor, 5-year old Sosuke lives a...",39.586760,"[{""name"": ""Studio Ghibli"", ""id"": 10342}, {""nam...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2008-07-19,187479518,100.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Welcome To A World Where Anything Is Possible.,Ponyo,7.5,926
1709,30000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 878, ...",NaN,192577,[],ja,キャプテンハーロック,Space Pirate Captain Harlock and his fearless ...,14.726338,"[{""name"": ""Toei Animation Company"", ""id"": 3116}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2013-09-07,17137302,115.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,NaN,Space Pirate Captain Harlock,6.5,356
1987,24000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 16, ""na...",NaN,4935,"[{""id"": 334, ""name"": ""flying""}, {""id"": 616, ""n...",ja,ハウルの動く城,"When Sophie, a shy young woman, is cursed with...",49.549984,"[{""name"": ""Studio Ghibli"", ""id"": 10342}, {""nam...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2004-11-19,234710455,119.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The two lived there,Howl's Moving Castle,8.2,1991
2247,26500000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",NaN,128,"[{""id"": 1721, ""name"": ""fight""}, {""id"": 1994, ""...",ja,もののけ姫,"Ashitaka, a prince of the disappearing Ainu tr...",60.732738,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1997-07-12,159375308,134.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The Fate Of The World Rests On The Courage Of ...,Princess Mononoke,8.2,1983
2258,20000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 14, ""...",NaN,8953,"[{""id"": 392, ""name"": ""england""}, {""id"": 1436, ...",ja,Steamboy,After receiving a package from his Grandfather...,9.129808,"[{""name"": ""Bandai Visual Company"", ""id"": 528},...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2004-07-17,0,126.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,He will save the future.,Steamboy,6.4,102
2294,15000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 12, ""na...",http://movies.disney.com/spirited-away,129,"[{""id"": 616, ""name"": ""witch""}, {""id"": 970, ""na...",ja,千と千尋の神隠し,A ten year old girl who wanders away from her ...,118.968562,"[{""name"": ""Studio Ghibli"", ""id"": 10342}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2001-07-20,274925095,125.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The tunnel led Chihiro to a mysterious town...,Spirited Away,8.3,3840
2888,12000000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...",http://www.office-kitano.co.jp/brother/index.html,327,"[{""id"": 380, ""name"": ""brother brother relation...",ja,Brother,A Japanese Yakuza gangster’s deadly existence ...,5.327714,"[{""name"": ""Bandai Visual Company"", ""id"": 528},...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2000-09-09,15250000,114.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Are You Japanese?,Brother,6.8,107
2900,12000000,"[{""id"": 878, ""name"": ""Science Fiction""}]",NaN,61984,[],ja,Space Battleship Yamato,"In 2199, five years after the Gamilons began a...",5.158067,"[{""name"": ""Tokyo Broadcasting System (TBS)"", ""...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2010-12-01,11212294,131.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,NaN,Space Battleship Yamato,6.3,59
2908,0,"[{""id"": 18, ""name"": ""Drama""}]",NaN,13889,[],ja,まあだだよ,This film tells the story of professor Uehida ...,2.930853,"[{""name"": ""Tokuma Shoten"", ""id"": 1779}, {""name...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1993-04-17,0,134.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Madadayo,7.5,20
3296,8000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://www.bandaivisual.co.jp/akira/,149,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",ja,アキラ,Childhood friends Tetsuo and Kaneda are pulled...,39.338097,"[{""name"": ""Bandai Visual Company"", ""id"": 528},...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1988-07-16,553171,124.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Neo-Tokyo is about to E.X.P.L.O.D.E.,Akira,7.8,773
3542,5500000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.r-100.com/,193722,"[{""id"": 7089, ""name"": ""dominatrix""}, {""id"": 15...",ja,R100,Ruthless dominatrixes pursue a mild-mannered s...,3.213920,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2013-10-05,0,100.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,M For Father,R100,5.4,31
3901,16000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://movies.warnerbros.com/pk3/,10991,"[{""id"": 1262, ""name"": ""mountains""}, {""id"": 280...",ja,Pokémon 3: The Movie,When Molly Hale's sadness of her father's disa...,9.188850,"[{""name"": ""TV Tokyo"", ""id"": 3034}, {""name"": ""4...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2000-07-08,68411275,93.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Pokémon: Spell of the Unknown,Pokémon: Spell of the Unknown,5.9,137
4344,1000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 27, ""...",NaN,10643,"[{""id"": 233, ""name"": ""japan""}, {""id"": 1299, ""n...",ja,Gojira ni-sen mireniamu,Godzilla saves Tokyo from a flying saucer that...,3.322721,"[{""name"": ""Toho Film (Eiga) Co. Ltd."", ""id"": 6...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1999-12-11,10037390,107.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Get ready to crumble.,Godzilla 2000,5.9,43
4535,2000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...",NaN,346,"[{""id"": 233, ""name"": ""japan""}, {""id"": 1462, ""n...",ja,七人の侍,A samurai answers a village's request for prot...,39.756748,"[{""name"": ""Toho Company"", ""id"": 882}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1954-04-26,271841,207.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The Mighty Warriors Who Became the Seven Natio...,Seven Samurai,8.2,878
4792,20000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 27, ""name...",NaN,36095,"[{""id"": 233, ""name"": ""japan""}, {""id"": 549, ""na...",ja,キュア,A wave of gruesome murders is sweeping Tokyo. ...,0.212443,"[{""name"": ""Daiei Studios"", ""id"": 881}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1997-11-06,99000,111.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Madness. Terror. Murder.,Cure,7.4,63

In [12]:
df[df['original_language']== 'ja' ]['budget'].mean()

14293606.1875

In [13]:
df.groupby('original_language').mean().loc['ja']

budget          1.429361e+07
id              5.389425e+04
popularity      2.566379e+01
revenue         6.602892e+07
runtime         1.225000e+02
vote_average    7.050000e+00
vote_count      7.157500e+02
Name: ja, dtype: float64

In [17]:
df.groupby('original_language').mean().loc['ja']['budget']

14293606.1875

In [24]:
df[~(df['budget'] == 0)].groupby('original_language').mean().loc['ja']['budget']

15246513.266666668

In [31]:
df[(df['budget'] != 0) & (df['original_language'] == 'ja' )].mean()['budget']

15246513.266666668

In [34]:
df[df['budget'] == 0].groupby('original_language').count()['budget']

original_language
ar      2
cn      5
cs      2
da      1
de     11
el      1
en    921
es      8
fa      2
fr     31
he      2
hi     10
hu      1
it      6
ja      1
ko      4
ky      1
nl      1
pt      6
ro      1
ru      3
sl      1
sv      4
ta      2
th      1
zh      9
Name: budget, dtype: int64

In [42]:
df.groupby('original_language').describe()

                   budget                                                      \
                    count          mean           std         min         25%
original_language
af                    1.0  3.000000e+06           NaN   3000000.0   3000000.0
ar                    2.0  0.000000e+00  0.000000e+00         0.0         0.0
cn                   12.0  1.072641e+07  1.245921e+07         0.0         0.0
cs                    2.0  0.000000e+00  0.000000e+00         0.0         0.0
da                    7.0  9.742857e+06  1.207834e+07         0.0   2550000.0
de                   27.0  8.616354e+06  1.910675e+07         0.0         0.0
el                    1.0  0.000000e+00           NaN         0.0         0.0
en                 4505.0  3.039436e+07  4.150614e+07         0.0   1000000.0
es                   32.0  5.847683e+06  8.443275e+06         0.0    165000.0
fa                    4.0  2.450000e+05  3.796051e+05         0.0         0.0
fr                   70.0  8.480997e+06  1.568539e+07         0.0         0.0
he                    3.0  6.666667e+05  1.154701e+06         0.0         0.0
hi                   19.0  1.715789e+06  2.749447e+06         0.0         0.0
hu                    1.0  0.000000e+00           NaN         0.0         0.0
id                    2.0  1.050000e+06  7.071068e+04   1000000.0   1025000.0
is                    1.0  1.000000e+01           NaN        10.0        10.0
it                   14.0  2.967859e+06  5.049660e+06         0.0         0.0
ja                   16.0  1.429361e+07  1.194324e+07         0.0   4625000.0
ko                   11.0  1.429091e+07  2.177179e+07         0.0         0.0
ky                    1.0  0.000000e+00           NaN         0.0         0.0
nb                    1.0  3.500000e+06           NaN   3500000.0   3500000.0
nl                    4.0  7.375000e+06  9.303897e+06         0.0   3000000.0
no                    1.0  8.000000e+05           NaN    800000.0    800000.0
pl                    1.0  2.159280e+06           NaN   2159280.0   2159280.0
ps                    1.0  4.600000e+04           NaN     46000.0     46000.0
pt                    9.0  1.133333e+06  1.722643e+06         0.0         0.0
ro                    2.0  4.262550e+05  6.028156e+05         0.0    213127.5
ru                   11.0  1.397273e+07  1.351030e+07         0.0   2100000.0
sl                    1.0  0.000000e+00           NaN         0.0         0.0
sv                    5.0  5.000000e+06  1.118034e+07         0.0         0.0
ta                    2.0  0.000000e+00  0.000000e+00         0.0         0.0
te                    1.0  4.000000e+07           NaN  40000000.0  40000000.0
th                    3.0  4.833333e+06  4.368447e+06         0.0   3000000.0
tr                    1.0  1.000000e+07           NaN  10000000.0  10000000.0
vi                    1.0  1.300000e+06           NaN   1300000.0   1300000.0
xx                    1.0  1.200000e+07           NaN  12000000.0  12000000.0
zh                   27.0  2.202560e+07  2.725664e+07         0.0         0.0

                                                            id                 \
                          50%         75%          max   count           mean
original_language
af                  3000000.0   3000000.0    3000000.0     1.0     868.000000
ar                        0.0         0.0          0.0     2.0   83505.000000
cn                  6000000.0  20750000.0   36000000.0    12.0  109470.500000
cs                        0.0         0.0          0.0     2.0  185196.000000
da                  6500000.0  10800000.0   35000000.0     7.0   33440.714286
de                  1500000.0   6250000.0   92620000.0    27.0   63369.518519
el                        0.0         0.0          0.0     1.0   38810.000000
en                 15000000.0  40000000.0  380000000.0  4505.0   55788.758047
es                  2000000.0   6200000.0   35000000.0    32.0   73720.937500
fa                    90000.0    335000.0     800000.0     4.0   38974.000000
fr                  1672000.0  10000000.0   97250400.0    70.0   62312.171429
he                        0.0   1000000.0    2000000.0     3.0   16428.333333
hi                        0.0   1725000.0    7700000.0    19.0   86905.526316
hu                        0.0         0.0          0.0     1.0   41508.000000
id                  1050000.0   1075000.0    1100000.0     2.0  109003.500000
is                       10.0        10.0         10.0     1.0  217708.000000
it                   100015.0   4050000.0   15000000.0    14.0   64481.857143
ja                 13500000.0  21000000.0   41677699.0    16.0   53894.250000
ko                  8000000.0  13500000.0   70000000.0    11.0   82569.545455
ky                        0.0         0.0          0.0     1.0  295914.000000
nb                  3500000.0   3500000.0    3500000.0     1.0   46146.000000
nl                  4250000.0   8625000.0   21000000.0     4.0   12169.500000
no                   800000.0    800000.0     800000.0     1.0   14451.000000
pl                  2159280.0   2159280.0    2159280.0     1.0  209274.000000
ps                    46000.0     46000.0      46000.0     1.0   14757.000000
pt                        0.0   2900000.0    4000000.0     9.0  136400.444444
ro                   426255.0    639382.5     852510.0     2.0  173237.500000
ru                  7000000.0  25500000.0   36500000.0    11.0  105219.000000
sl                        0.0         0.0          0.0     1.0  385636.000000
sv                        0.0         0.0   25000000.0     5.0   13241.200000
ta                        0.0         0.0          0.0     2.0  270824.500000
te                 40000000.0  40000000.0   40000000.0     1.0  256040.000000
th                  6000000.0   7250000.0    8500000.0     3.0   17554.666667
tr                 10000000.0  10000000.0   10000000.0     1.0   11818.000000
vi                  1300000.0   1300000.0    1300000.0     1.0   25784.000000
xx                 12000000.0  12000000.0   12000000.0     1.0   62204.000000
zh                 12000000.0  35500000.0   94000000.0    27.0  107819.222222

                   ... vote_average       vote_count                           \
                   ...          75%   max      count        mean          std
original_language  ...
af                 ...        6.900   6.9        1.0   94.000000          NaN
ar                 ...        7.550   7.8        2.0   53.500000     2.121320
cn                 ...        6.700   7.2       12.0  220.916667   243.485470
cs                 ...        6.325   7.0        2.0   12.000000    14.142136
da                 ...        7.750   7.9        7.0  450.428571   434.369987
de                 ...        7.400   8.0       27.0  242.444444   331.373637
el                 ...        6.900   6.9        1.0  332.000000          NaN
en                 ...        6.800  10.0     4505.0  719.023751  1263.358181
es                 ...        7.225   7.8       32.0  301.875000   549.329430
fa                 ...        7.725   7.8        4.0  155.250000   213.629547
fr                 ...        7.100   7.9       70.0  228.828571   414.528018
he                 ...        7.700   7.8        3.0  112.666667   154.480851
hi                 ...        7.200   7.4       19.0   44.000000    51.944415
hu                 ...        6.500   6.5        1.0   28.000000          NaN
id                 ...        7.450   7.5        2.0  632.500000   597.505230
is                 ...        6.900   6.9        1.0   26.000000          NaN
it                 ...        7.525   8.1       14.0  403.928571   661.484050
ja                 ...        7.900   8.3       16.0  715.750000  1060.489101
ko                 ...        7.300   8.0       11.0  588.818182   930.690799
ky                 ...        0.000   0.0        1.0    0.000000          NaN
nb                 ...        6.700   6.7        1.0  583.000000          NaN
nl                 ...        7.325   7.7        4.0   92.750000   125.577002
no                 ...        6.100   6.1        1.0  311.000000          NaN
pl                 ...        7.100   7.1        1.0  260.000000          NaN
ps                 ...        6.300   6.3        1.0   32.000000          NaN
pt                 ...        7.800   8.1        9.0  321.444444   582.814746
ro                 ...        5.475   7.3        2.0   78.000000   110.308658
ru                 ...        7.000   7.7       11.0   95.181818   108.164521
sl                 ...        6.000   6.0        1.0    1.000000          NaN
sv                 ...        7.700   7.8        5.0   87.000000    39.401777
ta                 ...        6.275   6.7        2.0    4.000000     1.414214
te                 ...        7.500   7.5        1.0  135.000000          NaN
th                 ...        6.400   6.8        3.0  108.333333    88.940055
tr                 ...        4.300   4.3        1.0    7.000000          NaN
vi                 ...        5.000   5.0        1.0    1.000000          NaN
xx                 ...        7.100   7.1        1.0  109.000000          NaN
zh                 ...        7.000   7.6       27.0  146.592593   213.453699


                     min     25%    50%     75%      max
original_language
af                  94.0   94.00   94.0   94.00     94.0
ar                  52.0   52.75   53.5   54.25     55.0
cn                   5.0   54.25  121.0  276.25    831.0
cs                   2.0    7.00   12.0   17.00     22.0
da                  65.0   73.00  207.0  904.00    927.0
de                   3.0   17.50   61.0  420.50   1037.0
el                 332.0  332.00  332.0  332.00    332.0
en                   0.0   58.00  251.0  788.00  13752.0
es                   4.0   27.50  177.5  309.75   3041.0
fa                  17.0   21.50   67.5  201.25    469.0
fr                   0.0   32.00  134.5  284.50   3310.0
he                  20.0   23.50   27.0  159.00    291.0
hi                   0.0    8.00   29.0   60.50    221.0
hu                  28.0   28.00   28.0   28.00     28.0
id                 210.0  421.25  632.5  843.75   1055.0
is                  26.0   26.00   26.0   26.00     26.0
it                   6.0   20.00  108.5  571.75   2311.0
ja                  20.0   62.00  140.0  890.00   3840.0
ko                  28.0   76.00  193.0  446.50   2854.0
ky                   0.0    0.00    0.0    0.00      0.0
nb                 583.0  583.00  583.0  583.00    583.0
nl                   3.0   19.50   45.5  118.75    277.0
no                 311.0  311.00  311.0  311.00    311.0
pl                 260.0  260.00  260.0  260.00    260.0
ps                  32.0   32.00   32.0   32.00     32.0
pt                   0.0    9.00  126.0  242.00   1814.0
ro                   0.0   39.00   78.0  117.00    156.0
ru                   7.0   23.00   47.0  129.00    357.0
sl                   1.0    1.00    1.0    1.00      1.0
sv                  42.0   63.00   76.0  115.00    139.0
ta                   3.0    3.50    4.0    4.50      5.0
te                 135.0  135.00  135.0  135.00    135.0
th                   6.0   79.00  152.0  159.50    167.0
tr                   7.0    7.00    7.0    7.00      7.0
vi                   1.0    1.00    1.0    1.00      1.0
xx                 109.0  109.00  109.0  109.00    109.0
zh                   3.0   23.00   55.0  195.00    927.0

[37 rows x 56 columns]

In [53]:
df.groupby('original_language').describe().columns

MultiIndex([(      'budget', 'count'),
            (      'budget',  'mean'),
            (      'budget',   'std'),
            (      'budget',   'min'),
            (      'budget',   '25%'),
            (      'budget',   '50%'),
            (      'budget',   '75%'),
            (      'budget',   'max'),
            (          'id', 'count'),
            (          'id',  'mean'),
            (          'id',   'std'),
            (          'id',   'min'),
            (          'id',   '25%'),
            (          'id',   '50%'),
            (          'id',   '75%'),
            (          'id',   'max'),
            (  'popularity', 'count'),
            (  'popularity',  'mean'),
            (  'popularity',   'std'),
            (  'popularity',   'min'),
            (  'popularity',   '25%'),
            (  'popularity',   '50%'),
            (  'popularity',   '75%'),
            (  'popularity',   'max'),
            (     'revenue', 'count'),
            (     'revenue',  'mean'),
            (     'revenue',   'std'),
            (     'revenue',   'min'),
            (     'revenue',   '25%'),
            (     'revenue',   '50%'),
            (     'revenue',   '75%'),
            (     'revenue',   'max'),
            (     'runtime', 'count'),
            (     'runtime',  'mean'),
            (     'runtime',   'std'),
            (     'runtime',   'min'),
            (     'runtime',   '25%'),
            (     'runtime',   '50%'),
            (     'runtime',   '75%'),
            (     'runtime',   'max'),
            ('vote_average', 'count'),
            ('vote_average',  'mean'),
            ('vote_average',   'std'),
            ('vote_average',   'min'),
            ('vote_average',   '25%'),
            ('vote_average',   '50%'),
            ('vote_average',   '75%'),
            ('vote_average',   'max'),
            (  'vote_count', 'count'),
            (  'vote_count',  'mean'),
            (  'vote_count',   'std'),
            (  'vote_count',   'min'),
            (  'vote_count',   '25%'),
            (  'vote_count',   '50%'),
            (  'vote_count',   '75%'),
            (  'vote_count',   'max')],
           )

In [54]:
df.groupby('original_language').describe()['runtime']['25%']

original_language
af     94.00
ar     90.00
cn     97.25
cs     96.75
da    110.00
de     90.00
el     94.00
en     93.00
es     99.75
fa     89.75
fr     95.00
he    102.00
hi    120.50
hu    140.00
id    104.50
is     85.00
it     90.00
ja    110.00
ko    117.00
ky    135.00
nb    103.00
nl    103.00
no     91.00
pl     80.00
ps     83.00
pt    106.00
ro    106.25
ru     95.00
sl     83.00
sv    109.00
ta    158.75
te    159.00
th    103.00
tr    122.00
vi    135.00
xx    100.00
zh    102.00
Name: 25%, dtype: float64

In [61]:
df.groupby('original_language').describe()['runtime']['25%'].iloc[2]

97.25

In [67]:
df.groupby('original_language').describe()['runtime']['25%'].columns

AttributeError: 'Series' object has no attribute 'columns'

In [68]:
df.groupby('original_language').describe()['runtime']['25%'].values

array([ 94.  ,  90.  ,  97.25,  96.75, 110.  ,  90.  ,  94.  ,  93.  ,
        99.75,  89.75,  95.  , 102.  , 120.5 , 140.  , 104.5 ,  85.  ,
        90.  , 110.  , 117.  , 135.  , 103.  , 103.  ,  91.  ,  80.  ,
        83.  , 106.  , 106.25,  95.  ,  83.  , 109.  , 158.75, 159.  ,
       103.  , 122.  , 135.  , 100.  , 102.  ])

In [69]:
df.groupby('original_language').describe()['runtime']['25%'].index

Index(['af', 'ar', 'cn', 'cs', 'da', 'de', 'el', 'en', 'es', 'fa', 'fr', 'he',
       'hi', 'hu', 'id', 'is', 'it', 'ja', 'ko', 'ky', 'nb', 'nl', 'no', 'pl',
       'ps', 'pt', 'ro', 'ru', 'sl', 'sv', 'ta', 'te', 'th', 'tr', 'vi', 'xx',
       'zh'],
      dtype='object', name='original_language')

In [70]:
df.groupby('original_language').describe()['runtime']['25%']['af']

94.0

In [71]:
df.groupby('original_language')['revenue'].max()

original_language
af       9879971
ar             0
cn     156844753
cs             0
da     170000000
de      92180910
el        110197
en    2787965087
es      99067206
fa        900000
fr     173921954
he      11125849
hi      46000000
hu             0
id       4105187
is            11
it      14500000
ja     274925095
ko      88489643
ky             0
nb       4159678
nl      26193068
no       1984662
pl      10700000
ps             0
pt      30641770
ro       1185783
ru      32000000
sl             0
sv             0
ta             0
te     100000000
th      27165581
tr             0
vi        639000
xx      55260558
zh     213525736
Name: revenue, dtype: int64

In [89]:
df.groupby('original_language')['revenue'].max()['ja']

274925095

In [73]:
df.groupby('original_language')['revenue'].idxmax()

original_language
af    3936
ar    4164
cn    1357
cs    2906
da    4586
de    2724
el    4605
en       0
es    3562
fa    4695
fr    1260
he    4104
hi    3228
hu    2894
id    4326
is    3131
it    4672
ja    2294
ko    2877
ky    4275
nb    3845
nl    2052
no    4464
pl    3999
ps    4523
pt    3866
ro    4434
ru    3733
sl    4510
sv    2474
ta    2271
te    1290
th    3518
tr    3231
vi    4272
xx    2787
zh    2515
Name: revenue, dtype: int64

In [133]:
df.iloc[df.groupby('original_language')['revenue'].idxmax()]

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
3936,3000000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...",http://www.tsotsimovie.com/,868,"[{""id"": 100, ""name"": ""slum""}, {""id"": 1009, ""na...",af,Tsotsi,The South African multi-award winning film abo...,2.504169,"[{""name"": ""Movieworld Productions"", ""id"": 563}...","[{""iso_3166_1"": ""ZA"", ""name"": ""South Africa""}]",2005-08-18,9879971,94.0,"[{""iso_639_1"": ""af"", ""name"": ""Afrikaans""}, {""i...",Released,In this world... Redemption comes just once.,Tsotsi,6.9,94
4164,0,"[{""id"": 99, ""name"": ""Documentary""}, {""id"": 18,...",http://www.thesquarefilm.com/,159037,"[{""id"": 187056, ""name"": ""woman director""}]",ar,The Square,"The Square, a new film by Jehane Noujaim (Cont...",4.892203,"[{""name"": ""Roast Beef Productions"", ""id"": 7266...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2013-06-07,0,88.0,"[{""iso_639_1"": ""ar"", ""name"": ""\u0627\u0644\u06...",Released,What does it mean to risk your life for your i...,The Square,7.8,55
1357,36000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...",NaN,365222,"[{""id"": 5565, ""name"": ""biography""}]",cn,葉問3,When a band of brutal gangsters led by a crook...,19.167377,"[{""name"": ""Mandarin Films Distribution Co."", ""...","[{""iso_3166_1"": ""HK"", ""name"": ""Hong Kong""}]",2015-12-19,156844753,105.0,"[{""iso_639_1"": ""cn"", ""name"": ""\u5e7f\u5dde\u8b...",Released,NaN,Ip Man 3,6.5,379
2906,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",https://www.facebook.com/eastsidestorymovie,357837,"[{""id"": 246, ""name"": ""dancing""}, {""id"": 271, ""...",cs,Dancin' It's On,"This coming of age Dance Film, in the spirit o...",0.186234,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-10-16,0,89.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Post Production,Dancin' Like You've Never Seen Before,Dancin' It's On,4.3,2
4586,35000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,9029,"[{""id"": 585, ""name"": ""casino""}, {""id"": 612, ""n...",da,What Happens in Vegas,"During a wild vacation in Las Vegas, career wo...",38.100488,"[{""name"": ""Twentieth Century Fox Film Corporat...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2008-05-07,170000000,99.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Get Lucky,What Happens in Vegas,5.8,923
2724,18339750,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 36, ""name...",http://www.downfallthefilm.com/,613,"[{""id"": 220, ""name"": ""berlin""}, {""id"": 351, ""n...",de,Der Untergang,"In April of 1945, Germany stands at the brink ...",32.445895,"[{""name"": ""Degeto Film"", ""id"": 986}, {""name"": ...","[{""iso_3166_1"": ""AT"", ""name"": ""Austria""}, {""is...",2004-09-08,92180910,156.0,"[{""iso_639_1"": ""hu"", ""name"": ""Magyar""}, {""iso_...",Released,"April 1945, a nation awaits its...Downfall",Downfall,7.7,1037
4605,0,"[{""id"": 18, ""name"": ""Drama""}]",http://www.dogtooth.gr/,38810,"[{""id"": 255, ""name"": ""male nudity""}, {""id"": 29...",el,Κυνόδοντας,Three teenagers are confined to an isolated co...,28.858238,"[{""name"": ""Greek Film Center"", ""id"": 7254}, {""...","[{""iso_3166_1"": ""GR"", ""name"": ""Greece""}]",2009-06-01,110197,94.0,"[{""iso_639_1"": ""el"", ""name"": ""\u03b5\u03bb\u03...",Released,The cat is the most feared animal there is!,Dogtooth,6.9,332
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
3562,5500000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,211954,"[{""id"": 1338, ""name"": ""bachelor""}, {""id"": 1554...",es,No se Aceptan Devoluciones,"Valentin is Acapulco's resident playboy, until...",9.597290,"[{""name"": ""Filmax"", ""id"": 3631}, {""name"": ""Sig...","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}]",2013-07-20,99067206,115.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}, ...",Released,Life doesn't care if you're ready.,Instructions Not Included,7.5,205
4695,180000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 35, ""name...",http://www.miramax.com/movie/children-of-heaven/,21334,"[{""id"": 1155, ""name"": ""brother sister relation...",fa,بچه‌های آسمان,Zohre's shoes are gone; her older brother Ali ...,7.072118,"[{""name"": ""The Institute for the Intellectual ...","[{""iso_3166_1"": ""IR"", ""name"": ""Iran""}]",1997-08-01,900000,89.0,"[{""iso_639_1"": ""fa"", ""name"": ""\u0641\u0627\u06...",Released,A Little Secret...Their Biggest Adventure!,Children of Heaven,7.8,112
1260,10000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",http://www.die-fabelhafte-welt-der-amelie.de,194,"[{""id"": 90, ""name"": ""paris""}, {""id"": 128, ""nam...",fr,Le fabuleux destin d'Amélie Poulain,"At a tiny Parisian café, the adorable yet pain...",73.720244,"[{""name"": ""France 3 Cin\u00e9ma"", ""id"": 591}, ...","[{""iso_3166_1"": ""FR"", ""name"": ""France""}, {""iso...",2001-04-25,173921954,122.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,One person can change your life forever.,Amélie,7.8,3310
4104,2000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 16, ""name...",http://waltzwithbashir.com,8885,"[{""id"": 536, ""name"": ""israel""}, {""id"": 537, ""n...",he,Vals Im Bashir,"Much awarded animated documentary, in which di...",14.082510,"[{""name"": ""Les Films d'Ici"", ""id"": 1848}, {""na...","[{""iso_3166_1"": ""IL"", ""name"": ""Israel""}, {""iso...",2008-06-25,11125849,90.0,"[{""iso_639_1"": ""he"", ""name"": ""\u05e2\u05b4\u05...",Released,NaN,Waltz with Bashir,7.8,291
3228,7700000,"[{""id"": 10749, ""name"": ""Romance""}]",http://www.facebook.com/YehJawaaniHaiDeewani,185008,[],hi,Yeh Jawaani Hai Deewani,Yeh Jawaani Hai Deewani features two polar opp...,3.353176,"[{""name"": ""Dharma Productions"", ""id"": 19146}]","[{""iso_3166_1"": ""IN"", ""name"": ""India""}]",2013-05-31,46000000,159.0,"[{""iso_639_1"": ""hi"", ""name"": ""\u0939\u093f\u09...",Released,NaN,Yeh Jawaani Hai Deewani,7.2,79
2894,0,"[{""id"": 10752, ""name"": ""War""}, {""id"": 18, ""nam...",NaN,41508,"[{""id"": 810, ""name"": ""budapest""}, {""id"": 1244,...",hu,Sorstalanság,An Hungarian youth comes of age at Buchenwald ...,1.906807,[],"[{""iso_3166_1"": ""HU"", ""name"": ""Hungary""}, {""is...",2005-02-10,0,140.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,You can close your eyes. You can turn away. Bu...,Fateless,6.5,28
4326,1100000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 53, ""nam...",http://www.sonyclassics.com/theraid/,94329,"[{""id"": 9730, ""name"": ""crime boss""}, {""id"": 14...",id,Serbuan maut,Deep in the heart of Jakarta's slums lies an i...,40.285095,"[{""name"": ""Celluloid Dreams"", ""id"": 860}, {""na...","[{""iso_3166_1"": ""ID"", ""name"": ""Indonesia""}, {""...",2011-09-08,4105187,101.0,"[{""iso_639_1"": ""id"", ""name"": ""Bahasa indonesia""}]",Released,"1 Ruthless Crime Lord, 20 Elite Cops, 30 Floor...",The Raid,7.3,1055
3131,10,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",http://hrosss.is/the-film/,217708,"[{""id"": 2673, ""name"": ""horse""}, {""id"": 3373, ""...",is,Hross í oss,A country romance about the human streak in th...,1.617943,"[{""name"": ""Filmhuset Gruppen"", ""id"": 68384}, {...","[{""iso_3166_1"": ""NO"", ""name"": ""Norway""}, {""iso...",2013-08-30,11,85.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Of Horses and Men,6.9,26
4672,200000,"[{""id"": 37, ""name"": ""Western""}]",NaN,391,"[{""id"": 2987, ""name"": ""gang war""}, {""id"": 4942...",it,Per un pugno di dollari,The Man With No Name enters the Mexican villag...,38.771062,"[{""name"": ""United Artists"", ""id"": 60}, {""name""...","[{""iso_3166_1"": ""IT"", ""name"": ""Italy""}, {""iso_...",1964-09-12,14500000,99.0,"[{""iso_639_1"": ""it"", ""name"": ""Italiano""}, {""is...",Released,"In his own way he is perhaps, the most dangero...",A Fistful of Dollars,7.6,883
2294,15000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 12, ""na...",http://movies.disney.com/spirited-away,129,"[{""id"": 616, ""name"": ""witch""}, {""id"": 970, ""na...",ja,千と千尋の神隠し,A ten year old girl who wanders away from her ...,118.968562,"[{""name"": ""Studio Ghibli"", ""id"": 10342}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2001-07-20,274925095,125.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The tunnel led Chihiro to a mysterious town...,Spirited Away,8.3,3840
2877,11000000,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...",http://www.hostmovie.com/,1255,"[{""id"": 1261, ""name"": ""river""}, {""id"": 1880, ""...",ko,괴물,Gang-du is a dim-witted man working at his fat...,27.655270,"[{""name"": ""Cineclick Asia"", ""id"": 685}, {""name...","[{""iso_3166_1"": ""KR"", ""name"": ""South Korea""}]",2006-07-27,88489643,119.0,"[{""iso_639_1"": ""ko"", ""name"": ""\ud55c\uad6d\uc5...",Released,Monsters are real.,The Host,6.7,537
4275,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 28, ""name...",NaN,295914,"[{""id"": 5565, ""name"": ""biography""}]",ky,Kurmanjan Datka. Queen of the Mountains,At a time when most females in Asia possess li...,0.077873,"[{""name"": ""Kirghizfilm"", ""id"": 40456}, {""name""...","[{""iso_3166_1"": ""KG"", ""name"": ""Kyrgyz Republic""}]",2014-08-22,0,135.0,"[{""iso_639_1"": ""ky"", ""name"": ""??????""}]",Released,NaN,Queen of the Mountains,0.0,0
3845,3500000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 27, ""na...",http://trolljegeren.no/,46146,"[{""id"": 414, ""name"": ""hunter""}, {""id"": 1262, ""...",nb,Trolljegeren,A group of students investigates a series of m...,12.982319,"[{""name"": ""Filmkameratene A/S"", ""id"": 1003}, {...","[{""iso_3166_1"": ""NO"", ""name"": ""Norway""}]",2010-10-29,4159678,103.0,"[{""iso_639_1"": ""no"", ""name"": ""Norsk""}]",Released,You believe it when you see it!,Troll Hunter,6.7,583
2052,21000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 53, ""name...",NaN,9075,"[{""id"": 930, ""name"": ""in love with enemy""}, {""...",nl,Zwartboek,In the Nazi-occupied Netherlands during World ...,13.906611,"[{""name"": ""CoBo Fund"", ""id"": 234}, {""name"": ""S...","[{""iso_3166_1"": ""NL"", ""name"": ""Netherlands""}, ...",2006-09-01,26193068,145.0,"[{""iso_639_1"": ""nl"", ""name"": ""Nederlands""}, {""...",Released,"To fight the enemy, she must become one of them.",Black Book,7.2,277
4464,800000,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 35, ""nam...",http://www.deadsnow.com,14451,"[{""id"": 1191, ""name"": ""norway""}, {""id"": 10327,...",no,Død snø,Eight medical students on a ski trip to Norway...,11.205726,"[{""name"": ""Euforia Film"", ""id"": 3553}, {""name""...","[{""iso_3166_1"": ""NO"", ""name"": ""Norway""}]",2009-01-09,1984662,91.0,"[{""iso_639_1"": ""no"", ""name"": ""Norsk""}]",Released,"Eins, Zwei, Die!",Dead Snow,6.1,311
3999,2159280,"[{""id"": 18, ""name"": ""Drama""}]",NaN,209274,"[{""id"": 745, ""name"": ""nun""}, {""id"": 1960, ""nam...",pl,Ida,"Poland, 1962. Anna is a novice, an orphan brou...",13.265432,"[{""name"": ""Danish Film Institute"", ""id"": 125},...","[{""iso_3166_1"": ""DK"", ""name"": ""Denmark""}, {""is...",2013-10-25,10700000,80.0,"[{""iso_639_1"": ""pl"", ""name"": ""Polski""}]",Released,NaN,Ida,7.1,260
4523,46000,"[{""id"": 18, ""name"": ""Drama""}]",NaN,14757,"[{""id"": 10183, ""name"": ""independent film""}]",ps,Osama,Teenage girl Osama cuts her hair and dresses l...,1.447734,"[{""name"": ""Hubert Bals Fund"", ""id"": 13413}, {""...","[{""iso_3166_1"": ""AF"", ""name"": ""Afghanistan""}, ...",2003-05-20,0,83.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,To save her family a girl must become a boy,Osama,6.3,32
3866,3300000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 80, ""name...",http://cidadededeus.globo.com/,598,"[{""id"": 255, ""name"": ""male nudity""}, {""id"": 54...",pt,Cidade de Deus,Cidade de Deus is a shantytown that started du...,44.356711,"[{""name"": ""O2 Filmes"", ""id"": 345}, {""name"": ""V...","[{""iso_3166_1"": ""BR"", ""name"": ""Brazil""}, {""iso...",2002-02-05,30641770,130.0,"[{""iso_639_1"": ""pt"", ""name"": ""Portugu\u00eas""}]",Released,"If you run you're dead... if you stay, you're ...",City of God,8.1,1814
4434,852510,"[{""id"": 18, ""name"": ""Drama""}]",NaN,2009,"[{""id"": 570, ""name"": ""rape""}, {""id"": 922, ""nam...",ro,"4 luni, 3 săptămîni și 2 zile","Gabita is pregnant, abortion is strictly forbi...",9.270133,"[{""name"": ""Saga Film"", ""id"": 859}, {""name"": ""M...","[{""iso_3166_1"": ""BE"", ""name"": ""Belgium""}, {""is...",2007-08-24,1185783,113.0,"[{""iso_639_1"": ""ro"", ""name"": ""Rom\u00e2n\u0103""}]",Released,At what moment do we begin to live?,"4 Months, 3 Weeks and 2 Days",7.3,156
3733,4200000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",NaN,3040,"[{""id"": 616, ""name"": ""witch""}, {""id"": 1552, ""n...",ru,Ночной дозор,"Among normal humans live the ""Others"" possessi...",12.540624,"[{""name"": ""Bazelevs Production"", ""id"": 1038}, ...","[{""iso_3166_1"": ""RU"", ""name"": ""Russia""}]",2004-06-27,32000000,114.0,"[{""iso_639_1"": ""de"", ""name"": ""Deutsch""}, {""iso...",Released,All That Stands Between Light And Darkness Is ...,Night Watch,6.3,210
4510,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,385636,"[{""id"": 445, ""name"": ""pornography""}, {""id"": 57...",sl,Julija in Alfa Romeo,"Tilen (18), an attractive high school student,...",0.061248,"[{""name"": ""Perfo Production"", ""id"": 34679}, {""...","[{""iso_3166_1"": ""SI"", ""name"": ""Slovenia""}]",2015-09-17,0,83.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Juliet and Alfa Romeo,6.0,1
2474,25000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",NaN,13491,"[{""id"": 156321, ""name"": ""tv movie""}]",sv,Arn: Tempelriddaren,"Arn, the son of a high-ranking Swedish noblema...",6.091033,"[{""name"": ""Danmarks Radio (DR)"", ""id"": 119}, {...","[{""iso_3166_1"": ""SE"", ""name"": ""Sweden""}]",2007-12-17,0,139.0,"[{""iso_639_1"": ""ar"", ""name"": ""\u0627\u0644\u06...",Released,A Knight in the Holy Land. A Woman in the Froz...,Arn: The Knight Templar,6.4,76
2271,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 36, ""name...",NaN,280871,"[{""id"": 2303, ""name"": ""mathematician""}, {""id"":...",ta,ராமானுஜன்,A prodigious Indian mathematician has to overc...,0.416179,"[{""name"": ""Camphor Cinema"", ""id"": 82667}]","[{""iso_3166_1"": ""IN"", ""name"": ""India""}]",2014-07-11,0,170.0,"[{""iso_639_1"": ""ta"", ""name"": ""\u0ba4\u0bae\u0b...",Released,NaN,Ramanujan,5.0,3
1290,40000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://baahubali.com/,256040,"[{""id"": 4152, ""name"": ""kingdom""}, {""id"": 6091,...",te,Baahubali: The Beginning,The young Shivudu is left as a foundling in a ...,16.254032,"[{""name"": ""Arka Media Works"", ""id"": 57946}]","[{""iso_3166_1"": ""IN"", ""name"": ""India""}]",2015-07-10,100000000,159.0,"[{""iso_639_1"": ""ml"", ""name"": """"}, {""iso_639_1""...",Released,NaN,Baahubali: The Beginning,7.5,135
3518,6000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,8982,"[{""id"": 188, ""name"": ""buddhism""}, {""id"": 2857,...",th,ต้มยำกุ้ง,"In Bangkok, the young Kham was raised by his f...",11.818320,"[{""name"": ""The Weinstein Company"", ""id"": 308},...","[{""iso_3166_1"": ""TH"", ""name"": ""Thailand""}, {""i...",2005-08-11,27165581,108.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Vengeance Knows No Mercy,The Protector,6.8,167
3231,10000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...",NaN,11818,"[{""id"": 2051, ""name"": ""intelligence""}, {""id"": ...",tr,Kurtlar vadisi - Irak,The movie opens with a fictionalized depiction...,1.465762,"[{""name"": ""Pana Film"", ""id"": 58135}]","[{""iso_3166_1"": ""TR"", ""name"": ""Turkey""}]",2006-02-03,0,122.0,"[{""iso_639_1"": ""ar"", ""name"": ""\u0627\u0644\u06...",Released,Some Men Are Born to be Heroes,Valley of the Wolves: Iraq,4.3,7
4272,1300000,"[{""id"": 18, ""name"": ""Drama""}]",http://www.journeyfromthefall.com/home.aspx,25784,"[{""id"": 2956, ""name"": ""vietnam""}, {""id"": 10183...",vi,Vượt Sóng,Thirteen years after the end of the Vietnam Wa...,0.072066,[],[],2006-02-22,639000,135.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Journey from the Fall,5.0,1
2787,12000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...",NaN,62204,"[{""id"": 4428, ""name"": ""stone age""}, {""id"": 159...",xx,La Guerre du feu,A colossal adventure odyssey that turns back t...,6.537986,"[{""name"": ""Belstar Productions"", ""id"": 999}, {...","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}, {""iso...",1981-12-15,55260558,100.0,"[{""iso_639_1"": ""xx"", ""name"": ""No Language""}]",Released,NaN,Quest for Fire,7.1,109
2515,17000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...",NaN,146,"[{""id"": 334, ""name"": ""flying""}, {""id"": 779, ""n...",zh,卧虎藏龙,Two warriors in pursuit of a stolen sword and ...,45.742254,"[{""name"": ""Sony Pictures Classics"", ""id"": 58},...","[{""iso_3166_1"": ""CN"", ""name"": ""China""}, {""iso_...",2000-10-01,213525736,120.0,"[{""iso_639_1"": ""zh"", ""name"": ""\u666e\u901a\u8b...",Released,"A timeless story of strength, secrets and two ...","Crouching Tiger, Hidden Dragon",7.2,927

In [79]:
df[(df.iloc[df.groupby('original_language')['revenue'].idxmax()]) && (df['original_language'] == 'ja')]

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
3936,3000000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...",http://www.tsotsimovie.com/,868,"[{""id"": 100, ""name"": ""slum""}, {""id"": 1009, ""na...",af,Tsotsi,The South African multi-award winning film abo...,2.504169,"[{""name"": ""Movieworld Productions"", ""id"": 563}...","[{""iso_3166_1"": ""ZA"", ""name"": ""South Africa""}]",2005-08-18,9879971,94.0,"[{""iso_639_1"": ""af"", ""name"": ""Afrikaans""}, {""i...",Released,In this world... Redemption comes just once.,Tsotsi,6.9,94
4164,0,"[{""id"": 99, ""name"": ""Documentary""}, {""id"": 18,...",http://www.thesquarefilm.com/,159037,"[{""id"": 187056, ""name"": ""woman director""}]",ar,The Square,"The Square, a new film by Jehane Noujaim (Cont...",4.892203,"[{""name"": ""Roast Beef Productions"", ""id"": 7266...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2013-06-07,0,88.0,"[{""iso_639_1"": ""ar"", ""name"": ""\u0627\u0644\u06...",Released,What does it mean to risk your life for your i...,The Square,7.8,55
1357,36000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...",NaN,365222,"[{""id"": 5565, ""name"": ""biography""}]",cn,葉問3,When a band of brutal gangsters led by a crook...,19.167377,"[{""name"": ""Mandarin Films Distribution Co."", ""...","[{""iso_3166_1"": ""HK"", ""name"": ""Hong Kong""}]",2015-12-19,156844753,105.0,"[{""iso_639_1"": ""cn"", ""name"": ""\u5e7f\u5dde\u8b...",Released,NaN,Ip Man 3,6.5,379
2906,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",https://www.facebook.com/eastsidestorymovie,357837,"[{""id"": 246, ""name"": ""dancing""}, {""id"": 271, ""...",cs,Dancin' It's On,"This coming of age Dance Film, in the spirit o...",0.186234,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-10-16,0,89.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Post Production,Dancin' Like You've Never Seen Before,Dancin' It's On,4.3,2
4586,35000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,9029,"[{""id"": 585, ""name"": ""casino""}, {""id"": 612, ""n...",da,What Happens in Vegas,"During a wild vacation in Las Vegas, career wo...",38.100488,"[{""name"": ""Twentieth Century Fox Film Corporat...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2008-05-07,170000000,99.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Get Lucky,What Happens in Vegas,5.8,923
2724,18339750,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 36, ""name...",http://www.downfallthefilm.com/,613,"[{""id"": 220, ""name"": ""berlin""}, {""id"": 351, ""n...",de,Der Untergang,"In April of 1945, Germany stands at the brink ...",32.445895,"[{""name"": ""Degeto Film"", ""id"": 986}, {""name"": ...","[{""iso_3166_1"": ""AT"", ""name"": ""Austria""}, {""is...",2004-09-08,92180910,156.0,"[{""iso_639_1"": ""hu"", ""name"": ""Magyar""}, {""iso_...",Released,"April 1945, a nation awaits its...Downfall",Downfall,7.7,1037
4605,0,"[{""id"": 18, ""name"": ""Drama""}]",http://www.dogtooth.gr/,38810,"[{""id"": 255, ""name"": ""male nudity""}, {""id"": 29...",el,Κυνόδοντας,Three teenagers are confined to an isolated co...,28.858238,"[{""name"": ""Greek Film Center"", ""id"": 7254}, {""...","[{""iso_3166_1"": ""GR"", ""name"": ""Greece""}]",2009-06-01,110197,94.0,"[{""iso_639_1"": ""el"", ""name"": ""\u03b5\u03bb\u03...",Released,The cat is the most feared animal there is!,Dogtooth,6.9,332
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
3562,5500000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,211954,"[{""id"": 1338, ""name"": ""bachelor""}, {""id"": 1554...",es,No se Aceptan Devoluciones,"Valentin is Acapulco's resident playboy, until...",9.597290,"[{""name"": ""Filmax"", ""id"": 3631}, {""name"": ""Sig...","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}]",2013-07-20,99067206,115.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}, ...",Released,Life doesn't care if you're ready.,Instructions Not Included,7.5,205
4695,180000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 35, ""name...",http://www.miramax.com/movie/children-of-heaven/,21334,"[{""id"": 1155, ""name"": ""brother sister relation...",fa,بچه‌های آسمان,Zohre's shoes are gone; her older brother Ali ...,7.072118,"[{""name"": ""The Institute for the Intellectual ...","[{""iso_3166_1"": ""IR"", ""name"": ""Iran""}]",1997-08-01,900000,89.0,"[{""iso_639_1"": ""fa"", ""name"": ""\u0641\u0627\u06...",Released,A Little Secret...Their Biggest Adventure!,Children of Heaven,7.8,112
1260,10000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",http://www.die-fabelhafte-welt-der-amelie.de,194,"[{""id"": 90, ""name"": ""paris""}, {""id"": 128, ""nam...",fr,Le fabuleux destin d'Amélie Poulain,"At a tiny Parisian café, the adorable yet pain...",73.720244,"[{""name"": ""France 3 Cin\u00e9ma"", ""id"": 591}, ...","[{""iso_3166_1"": ""FR"", ""name"": ""France""}, {""iso...",2001-04-25,173921954,122.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,One person can change your life forever.,Amélie,7.8,3310
4104,2000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 16, ""name...",http://waltzwithbashir.com,8885,"[{""id"": 536, ""name"": ""israel""}, {""id"": 537, ""n...",he,Vals Im Bashir,"Much awarded animated documentary, in which di...",14.082510,"[{""name"": ""Les Films d'Ici"", ""id"": 1848}, {""na...","[{""iso_3166_1"": ""IL"", ""name"": ""Israel""}, {""iso...",2008-06-25,11125849,90.0,"[{""iso_639_1"": ""he"", ""name"": ""\u05e2\u05b4\u05...",Released,NaN,Waltz with Bashir,7.8,291
3228,7700000,"[{""id"": 10749, ""name"": ""Romance""}]",http://www.facebook.com/YehJawaaniHaiDeewani,185008,[],hi,Yeh Jawaani Hai Deewani,Yeh Jawaani Hai Deewani features two polar opp...,3.353176,"[{""name"": ""Dharma Productions"", ""id"": 19146}]","[{""iso_3166_1"": ""IN"", ""name"": ""India""}]",2013-05-31,46000000,159.0,"[{""iso_639_1"": ""hi"", ""name"": ""\u0939\u093f\u09...",Released,NaN,Yeh Jawaani Hai Deewani,7.2,79
2894,0,"[{""id"": 10752, ""name"": ""War""}, {""id"": 18, ""nam...",NaN,41508,"[{""id"": 810, ""name"": ""budapest""}, {""id"": 1244,...",hu,Sorstalanság,An Hungarian youth comes of age at Buchenwald ...,1.906807,[],"[{""iso_3166_1"": ""HU"", ""name"": ""Hungary""}, {""is...",2005-02-10,0,140.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,You can close your eyes. You can turn away. Bu...,Fateless,6.5,28
4326,1100000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 53, ""nam...",http://www.sonyclassics.com/theraid/,94329,"[{""id"": 9730, ""name"": ""crime boss""}, {""id"": 14...",id,Serbuan maut,Deep in the heart of Jakarta's slums lies an i...,40.285095,"[{""name"": ""Celluloid Dreams"", ""id"": 860}, {""na...","[{""iso_3166_1"": ""ID"", ""name"": ""Indonesia""}, {""...",2011-09-08,4105187,101.0,"[{""iso_639_1"": ""id"", ""name"": ""Bahasa indonesia""}]",Released,"1 Ruthless Crime Lord, 20 Elite Cops, 30 Floor...",The Raid,7.3,1055
3131,10,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",http://hrosss.is/the-film/,217708,"[{""id"": 2673, ""name"": ""horse""}, {""id"": 3373, ""...",is,Hross í oss,A country romance about the human streak in th...,1.617943,"[{""name"": ""Filmhuset Gruppen"", ""id"": 68384}, {...","[{""iso_3166_1"": ""NO"", ""name"": ""Norway""}, {""iso...",2013-08-30,11,85.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Of Horses and Men,6.9,26
4672,200000,"[{""id"": 37, ""name"": ""Western""}]",NaN,391,"[{""id"": 2987, ""name"": ""gang war""}, {""id"": 4942...",it,Per un pugno di dollari,The Man With No Name enters the Mexican villag...,38.771062,"[{""name"": ""United Artists"", ""id"": 60}, {""name""...","[{""iso_3166_1"": ""IT"", ""name"": ""Italy""}, {""iso_...",1964-09-12,14500000,99.0,"[{""iso_639_1"": ""it"", ""name"": ""Italiano""}, {""is...",Released,"In his own way he is perhaps, the most dangero...",A Fistful of Dollars,7.6,883
2294,15000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 12, ""na...",http://movies.disney.com/spirited-away,129,"[{""id"": 616, ""name"": ""witch""}, {""id"": 970, ""na...",ja,千と千尋の神隠し,A ten year old girl who wanders away from her ...,118.968562,"[{""name"": ""Studio Ghibli"", ""id"": 10342}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2001-07-20,274925095,125.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The tunnel led Chihiro to a mysterious town...,Spirited Away,8.3,3840
2877,11000000,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 18, ""nam...",http://www.hostmovie.com/,1255,"[{""id"": 1261, ""name"": ""river""}, {""id"": 1880, ""...",ko,괴물,Gang-du is a dim-witted man working at his fat...,27.655270,"[{""name"": ""Cineclick Asia"", ""id"": 685}, {""name...","[{""iso_3166_1"": ""KR"", ""name"": ""South Korea""}]",2006-07-27,88489643,119.0,"[{""iso_639_1"": ""ko"", ""name"": ""\ud55c\uad6d\uc5...",Released,Monsters are real.,The Host,6.7,537
4275,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 28, ""name...",NaN,295914,"[{""id"": 5565, ""name"": ""biography""}]",ky,Kurmanjan Datka. Queen of the Mountains,At a time when most females in Asia possess li...,0.077873,"[{""name"": ""Kirghizfilm"", ""id"": 40456}, {""name""...","[{""iso_3166_1"": ""KG"", ""name"": ""Kyrgyz Republic""}]",2014-08-22,0,135.0,"[{""iso_639_1"": ""ky"", ""name"": ""??????""}]",Released,NaN,Queen of the Mountains,0.0,0
3845,3500000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 27, ""na...",http://trolljegeren.no/,46146,"[{""id"": 414, ""name"": ""hunter""}, {""id"": 1262, ""...",nb,Trolljegeren,A group of students investigates a series of m...,12.982319,"[{""name"": ""Filmkameratene A/S"", ""id"": 1003}, {...","[{""iso_3166_1"": ""NO"", ""name"": ""Norway""}]",2010-10-29,4159678,103.0,"[{""iso_639_1"": ""no"", ""name"": ""Norsk""}]",Released,You believe it when you see it!,Troll Hunter,6.7,583
2052,21000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 53, ""name...",NaN,9075,"[{""id"": 930, ""name"": ""in love with enemy""}, {""...",nl,Zwartboek,In the Nazi-occupied Netherlands during World ...,13.906611,"[{""name"": ""CoBo Fund"", ""id"": 234}, {""name"": ""S...","[{""iso_3166_1"": ""NL"", ""name"": ""Netherlands""}, ...",2006-09-01,26193068,145.0,"[{""iso_639_1"": ""nl"", ""name"": ""Nederlands""}, {""...",Released,"To fight the enemy, she must become one of them.",Black Book,7.2,277
4464,800000,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 35, ""nam...",http://www.deadsnow.com,14451,"[{""id"": 1191, ""name"": ""norway""}, {""id"": 10327,...",no,Død snø,Eight medical students on a ski trip to Norway...,11.205726,"[{""name"": ""Euforia Film"", ""id"": 3553}, {""name""...","[{""iso_3166_1"": ""NO"", ""name"": ""Norway""}]",2009-01-09,1984662,91.0,"[{""iso_639_1"": ""no"", ""name"": ""Norsk""}]",Released,"Eins, Zwei, Die!",Dead Snow,6.1,311
3999,2159280,"[{""id"": 18, ""name"": ""Drama""}]",NaN,209274,"[{""id"": 745, ""name"": ""nun""}, {""id"": 1960, ""nam...",pl,Ida,"Poland, 1962. Anna is a novice, an orphan brou...",13.265432,"[{""name"": ""Danish Film Institute"", ""id"": 125},...","[{""iso_3166_1"": ""DK"", ""name"": ""Denmark""}, {""is...",2013-10-25,10700000,80.0,"[{""iso_639_1"": ""pl"", ""name"": ""Polski""}]",Released,NaN,Ida,7.1,260
4523,46000,"[{""id"": 18, ""name"": ""Drama""}]",NaN,14757,"[{""id"": 10183, ""name"": ""independent film""}]",ps,Osama,Teenage girl Osama cuts her hair and dresses l...,1.447734,"[{""name"": ""Hubert Bals Fund"", ""id"": 13413}, {""...","[{""iso_3166_1"": ""AF"", ""name"": ""Afghanistan""}, ...",2003-05-20,0,83.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,To save her family a girl must become a boy,Osama,6.3,32
3866,3300000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 80, ""name...",http://cidadededeus.globo.com/,598,"[{""id"": 255, ""name"": ""male nudity""}, {""id"": 54...",pt,Cidade de Deus,Cidade de Deus is a shantytown that started du...,44.356711,"[{""name"": ""O2 Filmes"", ""id"": 345}, {""name"": ""V...","[{""iso_3166_1"": ""BR"", ""name"": ""Brazil""}, {""iso...",2002-02-05,30641770,130.0,"[{""iso_639_1"": ""pt"", ""name"": ""Portugu\u00eas""}]",Released,"If you run you're dead... if you stay, you're ...",City of God,8.1,1814
4434,852510,"[{""id"": 18, ""name"": ""Drama""}]",NaN,2009,"[{""id"": 570, ""name"": ""rape""}, {""id"": 922, ""nam...",ro,"4 luni, 3 săptămîni și 2 zile","Gabita is pregnant, abortion is strictly forbi...",9.270133,"[{""name"": ""Saga Film"", ""id"": 859}, {""name"": ""M...","[{""iso_3166_1"": ""BE"", ""name"": ""Belgium""}, {""is...",2007-08-24,1185783,113.0,"[{""iso_639_1"": ""ro"", ""name"": ""Rom\u00e2n\u0103""}]",Released,At what moment do we begin to live?,"4 Months, 3 Weeks and 2 Days",7.3,156
3733,4200000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",NaN,3040,"[{""id"": 616, ""name"": ""witch""}, {""id"": 1552, ""n...",ru,Ночной дозор,"Among normal humans live the ""Others"" possessi...",12.540624,"[{""name"": ""Bazelevs Production"", ""id"": 1038}, ...","[{""iso_3166_1"": ""RU"", ""name"": ""Russia""}]",2004-06-27,32000000,114.0,"[{""iso_639_1"": ""de"", ""name"": ""Deutsch""}, {""iso...",Released,All That Stands Between Light And Darkness Is ...,Night Watch,6.3,210
4510,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,385636,"[{""id"": 445, ""name"": ""pornography""}, {""id"": 57...",sl,Julija in Alfa Romeo,"Tilen (18), an attractive high school student,...",0.061248,"[{""name"": ""Perfo Production"", ""id"": 34679}, {""...","[{""iso_3166_1"": ""SI"", ""name"": ""Slovenia""}]",2015-09-17,0,83.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Juliet and Alfa Romeo,6.0,1
2474,25000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",NaN,13491,"[{""id"": 156321, ""name"": ""tv movie""}]",sv,Arn: Tempelriddaren,"Arn, the son of a high-ranking Swedish noblema...",6.091033,"[{""name"": ""Danmarks Radio (DR)"", ""id"": 119}, {...","[{""iso_3166_1"": ""SE"", ""name"": ""Sweden""}]",2007-12-17,0,139.0,"[{""iso_639_1"": ""ar"", ""name"": ""\u0627\u0644\u06...",Released,A Knight in the Holy Land. A Woman in the Froz...,Arn: The Knight Templar,6.4,76
2271,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 36, ""name...",NaN,280871,"[{""id"": 2303, ""name"": ""mathematician""}, {""id"":...",ta,ராமானுஜன்,A prodigious Indian mathematician has to overc...,0.416179,"[{""name"": ""Camphor Cinema"", ""id"": 82667}]","[{""iso_3166_1"": ""IN"", ""name"": ""India""}]",2014-07-11,0,170.0,"[{""iso_639_1"": ""ta"", ""name"": ""\u0ba4\u0bae\u0b...",Released,NaN,Ramanujan,5.0,3
1290,40000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://baahubali.com/,256040,"[{""id"": 4152, ""name"": ""kingdom""}, {""id"": 6091,...",te,Baahubali: The Beginning,The young Shivudu is left as a foundling in a ...,16.254032,"[{""name"": ""Arka Media Works"", ""id"": 57946}]","[{""iso_3166_1"": ""IN"", ""name"": ""India""}]",2015-07-10,100000000,159.0,"[{""iso_639_1"": ""ml"", ""name"": """"}, {""iso_639_1""...",Released,NaN,Baahubali: The Beginning,7.5,135
3518,6000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,8982,"[{""id"": 188, ""name"": ""buddhism""}, {""id"": 2857,...",th,ต้มยำกุ้ง,"In Bangkok, the young Kham was raised by his f...",11.818320,"[{""name"": ""The Weinstein Company"", ""id"": 308},...","[{""iso_3166_1"": ""TH"", ""name"": ""Thailand""}, {""i...",2005-08-11,27165581,108.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Vengeance Knows No Mercy,The Protector,6.8,167
3231,10000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...",NaN,11818,"[{""id"": 2051, ""name"": ""intelligence""}, {""id"": ...",tr,Kurtlar vadisi - Irak,The movie opens with a fictionalized depiction...,1.465762,"[{""name"": ""Pana Film"", ""id"": 58135}]","[{""iso_3166_1"": ""TR"", ""name"": ""Turkey""}]",2006-02-03,0,122.0,"[{""iso_639_1"": ""ar"", ""name"": ""\u0627\u0644\u06...",Released,Some Men Are Born to be Heroes,Valley of the Wolves: Iraq,4.3,7
4272,1300000,"[{""id"": 18, ""name"": ""Drama""}]",http://www.journeyfromthefall.com/home.aspx,25784,"[{""id"": 2956, ""name"": ""vietnam""}, {""id"": 10183...",vi,Vượt Sóng,Thirteen years after the end of the Vietnam Wa...,0.072066,[],[],2006-02-22,639000,135.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Journey from the Fall,5.0,1
2787,12000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...",NaN,62204,"[{""id"": 4428, ""name"": ""stone age""}, {""id"": 159...",xx,La Guerre du feu,A colossal adventure odyssey that turns back t...,6.537986,"[{""name"": ""Belstar Productions"", ""id"": 999}, {...","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}, {""iso...",1981-12-15,55260558,100.0,"[{""iso_639_1"": ""xx"", ""name"": ""No Language""}]",Released,NaN,Quest for Fire,7.1,109
2515,17000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""...",NaN,146,"[{""id"": 334, ""name"": ""flying""}, {""id"": 779, ""n...",zh,卧虎藏龙,Two warriors in pursuit of a stolen sword and ...,45.742254,"[{""name"": ""Sony Pictures Classics"", ""id"": 58},...","[{""iso_3166_1"": ""CN"", ""name"": ""China""}, {""iso_...",2000-10-01,213525736,120.0,"[{""iso_639_1"": ""zh"", ""name"": ""\u666e\u901a\u8b...",Released,"A timeless story of strength, secrets and two ...","Crouching Tiger, Hidden Dragon",7.2,927

In [83]:
df.iloc[df.groupby('original_language')['revenue'].idxmax()].columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [84]:
df2 = df.iloc[df.groupby('original_language')['revenue'].idxmax()]

In [86]:
df2[df2['original_language'] == 'ja']

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
2294,15000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 12, ""na...",http://movies.disney.com/spirited-away,129,"[{""id"": 616, ""name"": ""witch""}, {""id"": 970, ""na...",ja,千と千尋の神隠し,A ten year old girl who wanders away from her ...,118.968562,"[{""name"": ""Studio Ghibli"", ""id"": 10342}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2001-07-20,274925095,125.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The tunnel led Chihiro to a mysterious town...,Spirited Away,8.3,3840

In [121]:
df3 = df[df['original_language'] == 'ja']

In [130]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16 entries, 97 to 4792
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                16 non-null     int64
 1   genres                16 non-null     object
 2   homepage              5 non-null      object
 3   id                    16 non-null     int64
 4   keywords              16 non-null     object
 5   original_language     16 non-null     object
 6   original_title        16 non-null     object
 7   overview              16 non-null     object
 8   popularity            16 non-null     float64
 9   production_companies  16 non-null     object
 10  production_countries  16 non-null     object
 11  release_date          16 non-null     object
 12  revenue               16 non-null     int64
 13  runtime               16 non-null     float64
 14  spoken_languages      16 non-null     object
 15  status                16 non-null     object
 16  tagline               13 non-null     object
 17  title                 16 non-null     object
 18  vote_average          16 non-null     float64
 19  vote_count            16 non-null     int64
dtypes: float64(3), int64(4), object(13)
memory usage: 2.6+ KB

In [161]:
df3[df3['revenue'] == df3.max()['revenue']]

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
2294,15000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 12, ""na...",http://movies.disney.com/spirited-away,129,"[{""id"": 616, ""name"": ""witch""}, {""id"": 970, ""na...",ja,千と千尋の神隠し,A ten year old girl who wanders away from her ...,118.968562,"[{""name"": ""Studio Ghibli"", ""id"": 10342}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2001-07-20,274925095,125.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The tunnel led Chihiro to a mysterious town...,Spirited Away,8.3,3840